# Generated by Django 5.0 on 2023-12-08 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_date_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_posted',
        ),
    ]
